apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: multi-cluster-workloads
  namespace: argocd

spec:
  generators:
    - matrix:
        generators:

          - list:
              elements:
                - environment: prod
                  branch: prod
                  cluster: arn:aws:eks:ap-south-1:882640845424:cluster/prod-cluster

                - environment: dr
                  branch: prod
                  cluster: arn:aws:eks:ap-southeast-1:882640845424:cluster/dr-cluster

          - list:
              elements:
                - app: frontend
                - app: api
                - app: auth
                - app: database

  template:

    metadata:
      name: "{{app}}-{{environment}}"
      namespace: argocd

    spec:

      project: platform-project

      source:
        repoURL: https://github.com/Saurabh-dev-create/eks-gitops-platform.git
        targetRevision: "{{branch}}"
        path: apps/{{app}}

      destination:
        name: "{{cluster}}"
        namespace: "{{environment}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
