apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  
  labels:
    app: auth
    tier: auth
spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth
        tier: auth

    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: auth
        image: 882640845424.dkr.ecr.ap-south-1.amazonaws.com/auth:883ea91a03acb92dd7358c0b75f2670e825ab64f
        
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 3001

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
