mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

config:

  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    batch: {}

  exporters:

    otlp:
      endpoint: tempo.monitoring.svc.cluster.local:4317

      tls:
        insecure: true

    debug: {}

  service:

    pipelines:

      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]

      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]

      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]
