apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kyverno-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: kyverno.rules
    rules:

    - alert: KyvernoPolicyViolation
      expr: sum(increase(kyverno_admission_requests_total{request_allowed="false"}[2m])) > 0
      for: 10s

      labels:
        severity: warning

      annotations:
        summary: "Kyverno blocked a Kubernetes request"

        description: |
          Kyverno denied a deployment because it violated a security policy.
