mode: deployment

image:
  repository: otel/opentelemetry-collector-k8s
  tag: "0.130.1"

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    batch: {}
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

  exporters:
    otlp:
      endpoint: tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true

    debug: {}

  extensions:
    health_check: {}

  service:
    extensions:
      - health_check

    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlp, debug]
