apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: check-required-labels
      match:
        any:
          - resources:
              kinds:
                - Pod

      validate:
        message: "Pods must have 'app' and 'environment' labels."

        pattern:
          metadata:
            labels:
              app: "?*"
              environment: "?*"
