apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  
  labels:
    app: api
    tier: api
spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api
        tier: api

    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: api
        image: 882640845424.dkr.ecr.ap-south-1.amazonaws.com/api:62a75bc5edf916b375be15d42a0a9b9d8c8e0940
        
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5678

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySecionds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
